// Generated by Nexus UI from web/contract.ts. Do not edit: the next build overwrites it.
export {};

declare module 'nexus' {
  interface NexusContract {
    calls: {
      'garage:list': {
        input: void;
        output: {
          balance: number;
          vehicles: {
            model: string;
            label: string;
            class: 'compact' | 'motorcycle' | 'sports' | 'super' | 'suv';
            price: number;
            speed: number;
            acceleration: number;
            handling: number;
            owned: boolean;
          }[];
        };
      };
      'garage:buy': {
        input: { model: string };
        output: { balance: number };
        errors: {
          not_enough_money: { missing: number };
        };
      };
    };
    pushes: {
      'garage:balance': { balance: number };
    };
    client: {
      'garage:preview': { model: string };
    };
    state: {
      hud: { visible: boolean; speed: number; fuel: number; engine: number; street: string };
    };
    screens: {};
  }
}
