import type { ScreenDeclaration } from '../compiler';
import { luaKey, luaString } from '../contract/lua';

export interface ScreenInfo {
  /** The name Lua opens it by. */
  name: string;
  /** Path of the `.nexus` file, relative to the resource. */
  file: string;
  /** What its `<screen>` tag declares. A screen file without the tag gets the defaults. */
  declaration: ScreenDeclaration;
}

/**
 * Generates `nexus/screens.lua`: what the client runtime needs to know about each screen to
 * handle focus and Escape, which screen is the app on a surface, and the size of the browser
 * a world screen is drawn by. The size of any other screen and the cursor only matter to the
 * page and are left out.
 */
export function generateScreensLua(screens: readonly ScreenInfo[]): string {
  const rows = [...screens]
    .sort((a, b) => a.name.localeCompare(b.name))
    .map(({ name, declaration }) => {
      const fields = [
        `layer = ${luaString(declaration.layer)}`,
        `mouse = ${declaration.focus.mouse}`,
        `keyboard = ${declaration.focus.keyboard}`,
        `keepInput = ${declaration.keepInput}`,
        `escape = ${declaration.close === 'escape'}`,
      ];
      if (declaration.surface) fields.push(`surface = ${luaString(declaration.surface)}`);
      if (declaration.surface === 'world' && declaration.size) fields.push(`width = ${declaration.size.width}`, `height = ${declaration.size.height}`);
      return `    ${luaKey(name)} = { ${fields.join(', ')} },\n`;
    });
  return (
    '-- Generated by Nexus UI from the <screen> tags in web/screens. Do not edit: the next build overwrites it.\n\n' +
    (rows.length === 0 ? 'NexusScreens = {}\n' : `NexusScreens = {\n${rows.join('')}}\n`)
  );
}
