// Generated by Nexus UI from web/contract.ts. Do not edit: the next build overwrites it.
export {};

declare module 'nexus' {
  interface NexusContract {
    calls: {
      'worldtest:time': {
        input: void;
        output: { time: string };
      };
    };
    pushes: {
      'worldtest:ping': { nonce: number };
    };
    client: {
      'worldtest:hello': {
        address: string;
        opened: boolean;
        field: { x: number; y: number };
        button: { x: number; y: number };
        list: { x: number; y: number };
      };
      'worldtest:pong': { nonce: number };
      'worldtest:saw': { what: 'pointer' | 'click' | 'wheel' | 'text' | 'key'; detail: string };
    };
    state: {
      proof: {
        page: 'wait' | 'pass' | 'fail';
        post: 'wait' | 'pass' | 'fail';
        message: 'wait' | 'pass' | 'fail';
        pointer: 'wait' | 'pass' | 'fail';
        click: 'wait' | 'pass' | 'fail';
        wheel: 'wait' | 'pass' | 'fail';
        text: 'wait' | 'pass' | 'fail';
        key: 'wait' | 'pass' | 'fail';
      };
    };
    screens: {
      proof: { model: string; txd: string; texture: string };
    };
  }
}
