import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { contract, generate, generateLua, generateTypes, s } from '../../src/contract';
import { luaKey, luaString } from '../../src/contract/lua';
import { Lua } from '../support/lua';

const shop = contract({
  calls: {
    'shop:buy': {
      input: s.object({ item: s.string({ max: 40 }), amount: s.int({ min: 1, max: 100 }) }),
      output: s.object({ ok: s.boolean(), balance: s.int() }),
      rate: { limit: 5, per: 10 },
    },
    'shop:list': {
      output: s.array(
        s.object({
          item: s.string({ max: 40 }),
          kind: s.enum(['food', 'drink']),
          tags: s.optional(s.array(s.enum(['new', 'sale']))),
          owner: s.nullable(s.int()),
          prices: s.record(s.number()),
          'display-name': s.string(),
          exact: s.literal(5),
          nothing: s.object({}),
        }),
      ),
    },
    refresh: {},
  },
  pushes: { 'shop:stock': s.object({ item: s.string({ max: 40 }), stock: s.int({ min: 0 }) }) },
  client: { 'shop:preview': s.object({ item: s.string({ max: 40 }) }) },
  state: { hud: s.object({ health: s.int(), armour: s.int(), cash: s.int() }) },
});

describe('generateTypes', () => {
  it('writes the declarations that fill in NexusContract', () => {
    expect(generateTypes(shop)).toBe(`// Generated by Nexus UI from web/contract.ts. Do not edit: the next build overwrites it.
export {};

declare module 'nexus' {
  interface NexusContract {
    calls: {
      'shop:buy': {
        input: { item: string; amount: number };
        output: { ok: boolean; balance: number };
      };
      'shop:list': {
        input: void;
        output: {
          item: string;
          kind: 'food' | 'drink';
          tags?: ('new' | 'sale')[];
          owner?: number | null;
          prices: Record<string, number>;
          'display-name': string;
          exact: 5;
          nothing: Record<string, never>;
        }[];
      };
      refresh: {
        input: void;
        output: void;
      };
    };
    pushes: {
      'shop:stock': { item: string; stock: number };
    };
    client: {
      'shop:preview': { item: string };
    };
    state: {
      hud: { health: number; armour: number; cash: number };
    };
    screens: {};
  }
}
`);
  });

  it('writes empty sections for an empty contract, and takes the module and the source name', () => {
    const text = generateTypes(contract({}), { module: 'nexus-ui', source: 'ui/contract.ts' });
    expect(text).toContain('// Generated by Nexus UI from ui/contract.ts.');
    expect(text).toContain("declare module 'nexus-ui' {");
    expect(text).toContain('    calls: {};\n    pushes: {};\n    client: {};\n    state: {};\n');
  });

  it('quotes what TypeScript would not read as written', () => {
    const text = generateTypes(contract({ pushes: { a: s.object({ "it's": s.enum(["don't", 'a"b']), top: s.optional(s.nullable(s.string())) }) } }));
    expect(text).toContain(`a: { 'it\\'s': 'don\\'t' | 'a"b'; top?: string | null };`);
  });
});

describe('generateLua', () => {
  let lua: Lua;

  beforeAll(async () => {
    lua = await Lua.create();
  });

  afterAll(() => lua.close());

  it('writes a table with one validator per message and the rate limit of every call', async () => {
    await lua.run(generateLua(shop));
    const shape = await lua.run(`
      local names = {}
      for section, entries in pairs(NexusContract) do
          for name, entry in pairs(entries) do
              local kind = type(entry)
              if kind == 'table' then
                  kind = ('%s %s %d/%d'):format(type(entry.input), type(entry.output), entry.limit, entry.per)
              end
              names[#names + 1] = section .. ' ' .. name .. ' ' .. kind
          end
      end
      table.sort(names)
      return table.concat(names, '\\n')
    `);
    expect(shape).toBe(
      [
        'calls refresh function function 30/10',
        'calls shop:buy function function 5/10',
        'calls shop:list function function 30/10',
        'client shop:preview function',
        'pushes shop:stock function',
        'state hud function',
      ].join('\n'),
    );
  });

  it('defines one global and nothing else', async () => {
    const fresh = await Lua.create();
    const leaked = await fresh.run(`
      local before = {}
      for name in pairs(_G) do before[name] = true end
      load(${JSON.stringify(generateLua(shop))})()
      local added = {}
      for name in pairs(_G) do
          if not before[name] then added[#added + 1] = name end
      end
      return table.concat(added, ', ')
    `);
    expect(leaked).toBe('NexusContract');
    fresh.close();
  });

  it('names its source in the header and leaves the pattern helpers out when no schema needs them', () => {
    const text = generateLua(contract({ pushes: { a: s.object({ n: s.int() }) } }), { source: 'ui/contract.ts' });
    expect(text.startsWith('-- Generated by Nexus UI from ui/contract.ts. Do not edit: the next build overwrites it.\n')).toBe(true);
    expect(text).not.toContain('local function matches');
    expect(generateLua(contract({ pushes: { a: s.string({ pattern: /^[a-z]+$/ }) } }))).toContain('local function matches');
  });

  it('shares one constant between schemas that need the same one', () => {
    const point = s.object({ x: s.int(), y: s.int() });
    const text = generateLua(contract({ pushes: { a: point, b: point }, client: { c: s.object({ x: s.int(), y: s.int() }) } }));
    expect(text.match(/\{ x = true, y = true \}/g)).toHaveLength(1);
  });

  it('survives names and values that are not plain Lua', async () => {
    const odd = contract({
      pushes: {
        end: s.object({
          and: s.int(),
          'two words': s.enum(["it's", 'a\\b', 'line\nbreak', 'ünï']),
          nil: s.literal("quote'"),
        }),
      },
    });
    await lua.run(generateLua(odd));
    const check = (value: unknown): Promise<unknown> =>
      lua.call(`local ok, problem = NexusContract.pushes['end'](...) return ok and 'ok' or problem`, value);
    expect(await check({ and: 1, 'two words': "it's", nil: "quote'" })).toBe('ok');
    expect(await check({ and: 1, 'two words': 'line\nbreak', nil: "quote'" })).toBe('ok');
    expect(await check({ and: 1, 'two words': 'ünï', nil: "quote'" })).toBe('ok');
    expect(await check({ and: 1, 'two words': 'a\\b', nil: 'quote' })).toBe('nil: expected "quote\'"');
    expect(await check({ and: 1, 'two words': 'uni', nil: "quote'" })).toBe('two words: expected one of "it\'s", "a\\\\b", "line\\nbreak", "ünï"');
  });

  it('escapes strings byte for byte and brackets keys that are not names', () => {
    expect(luaString("it's a \\ test\n")).toBe("'it\\'s a \\\\ test\\n'");
    expect(luaString('é')).toBe("'\\195\\169'");
    expect(luaKey('health')).toBe('health');
    expect(luaKey('end')).toBe("['end']");
    expect(luaKey('shop:buy')).toBe("['shop:buy']");
  });
});

describe('generate', () => {
  it('returns both outputs', () => {
    const { types, lua } = generate(shop, { source: 'web/contract.ts' });
    expect(types).toBe(generateTypes(shop));
    expect(lua).toBe(generateLua(shop));
  });
});
